### ISSUE TITLE
Records 表格欄位增加

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#103]
- [x] 寫一個 SQL 可以直接修改資料庫的
- [x] 更新 build schema 那份資料
- [x] 增加 init.php 的內容 @chzhonge 

name | type | desc
---- | ---- | ----
doctor | string | 護理師留言

**Comment by TankTsai** [comment]
ALTER TABLE records ADD doctor text;

**Comment by PolarBearAndrew** [comment]
``` sql
ALTER TABLE records ADD doctor text;
```
