### ISSUE TITLE
Records 的 update 端點 

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#105]
* 重新測一次, 確認可以 update 部分欄位, 不用全部上傳
* 讓端點支援可以 update doctor 這個欄位

**Comment by chzhonge** [comment]
需要把API 要資料的部份，一起把doctor加上去嗎？
還是就更改Update_post就好了？

**Comment by PolarBearAndrew** [comment]
都加上去~
