### ISSUE TITLE
使用者資料更新 API

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#11]
### GET /api/v1/user/:id

* 取得某使用者筆的資料
* 記得不要全部的資料都丟回來喔~

#### returns 

``` js
data : {
    id : 123,
    name : '陳柏安',
    account : 'AndrewChen',
    profile : '/public/profile/123123.jpg',
}
```

******

### PUT /api/v1/user/:id

* 更新某使用者筆的資料
* 基本上是完全覆蓋所有的資料

#### params

name | type | desc
---- | ---- | ----
name | string |
account | string | 
password | string | 
type | string | 要檢查是否為合法的 value
profile | string | 要先完成這個 https://github.com/PolarBearAndrew/FE-HealthManager/issues/12

#### returns 

``` js
data : {
    id : 123,
}
```

**Comment by PolarBearAndrew** [comment]
@chzhonge  實作我想用 PUT, 如果有問題的話, 改回用 POST 也可以

**Comment by chzhonge** [comment]
CLOSE #11
