### ISSUE TITLE
上傳圖片並回傳路徑

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#12]
### POST /api/v1/upload/

* 上傳某個檔案後
* 回傳該檔案的路徑給我

#### params

name | type | desc
---- | ---- | ----
type | string | 哪種檔案
file.image | file | 

#### returns

``` js
data : {
    path : '/public/xxx/123123.jpg'
}
```

**Comment by PolarBearAndrew** [comment]
@chzhonge  我修定了 API path

**Comment by chzhonge** [comment]
close #12
