### ISSUE TITLE
DB - Records

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#21]
DB 新增資料表

* Records 用來記錄所有的飲食、運動
* 全部給他寫在同一個對惹
* 值需要 default null

### Records

name | type | desc
---- | ---- | ----
id | number, auto increment, P.K. |
title | string | 名稱
type | enum | 類別
image | string | 
descs | string | 
time | number | 時間(分鐘)
createdAt | dateTime | 建立時間
UserId | number, F.K | 

#### Records.type

value | desc
---- | ----
SPORTS | 運動
BREAKFAST | 早餐 
LUNCH | 午餐
DINNER | 晚餐

**Comment by TankTsai** [comment]
desc 是保留字，我改成 
```
descs
```

**Comment by PolarBearAndrew** [comment]
ok
