### ISSUE TITLE
更新 Records API

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#23]
#### PUT /api/v1/records/:id

name | type | desc
---- | ---- | ----
title | string | 名稱
type | enum | 類別
image | string | 
desc | string | 
time | number | 時間(分鐘)

#### returns

``` js
data : {
   id : 123,
}
```

**Comment by PolarBearAndrew** [comment]
@TankTsai  實作我想用 PUT, 如果有問題的話, 改回用 POST 也可以

**Comment by TankTsai** [comment]
OK
