### ISSUE TITLE
撰寫 init.php

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#68]
* 這是一個獨立的 php 檔案,  不仰賴 framework
* 呼叫該檔案就直接執行了

執行內容

1. 新增一個 user
1. 對該 user 新增 2 週的  Records
1. 在頁面上直接列表顯示上述新增的資料即可

注意內容

* user 用 admin/ admin, 已經存在的話就不新增
* 該 user 相關的 records 都清掉 , 用成新的
* records 的日期請選過去這兩個禮拜

**Comment by chzhonge** [comment]
admin/ admin 修改為 demo/demo
