### ISSUE TITLE
測試操作流程

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#94]
有 bug 就截圖好惹XD
或是有 err code 或是詳細的操作

**Comment by chzhonge** [comment]
[錯誤](https://commitpushrun.slack.com/files/zhong/F1G8DNTHU/________________________.png)

**Comment by chzhonge** [comment]
[管理者介面](https://commitpushrun.slack.com/files/zhong/F1G8DNTHU/________________________.png)
管理者介面我會跳Error。

**Comment by PolarBearAndrew** [comment]
有可能 
Records 有個欄位名稱修正

`createAt` -> `createdAt`

**Comment by PolarBearAndrew** [comment]
不然就是我再把我的 schemas build 一份給你們 XD

**Comment by PolarBearAndrew** [comment]
@chzhonge  你還有這方面的問題嗎
