### ISSUE TITLE
重新檢查一次文件

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/FE-HealthManager#99]
* 記得寫中文啊~
* 確認排版
* 匯入資料庫的 .sql 檔案記得給, 或是說明在原始黨的哪裡

沒問題就關掉這個 issue 吧

**Comment by PolarBearAndrew** [comment]
弄完後記得通知我

**Comment by TankTsai** [comment]
文件的部份我看起來沒問題，但是SQL檔案部分要放哪裡?
